# Generated by Django 5.1.3 on 2024-11-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('reset_pass', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('timeout', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('date_time_format', models.CharField(default='YYYY-MM-DD HH:MM:SS', max_length=100)),
                ('language', models.CharField(default='English', max_length=30)),
                ('organisation', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('memo', models.TextField(blank=True, null=True)),
                ('primary_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_group_users', to='myApp.group')),
                ('roles', models.ManyToManyField(related_name='users', to='myApp.role')),
                ('scopes', models.ManyToManyField(related_name='users', to='myApp.scope')),
                ('secondary_groups', models.ManyToManyField(related_name='secondary_group_users', to='myApp.group')),
            ],
        ),
    ]
