# Generated by Django 5.1.3 on 2024-11-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scopes',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_time_format',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
