# Generated by Django 5.1.3 on 2024-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_user_primary_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_pass',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
